name: Test poseidon-hs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
# https://github.com/actions/setup-haskell    
jobs:
  runhaskell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-haskell@v1.1
        with:
          ghc-version: 'latest'
          cabal-version: 'latest'
          enable-stack: true
          stack-version: 'latest'
      - run: stack test
