# https://kodimensional.dev/github-actions
name: CI

# Trigger the workflow on push or pull request, but only for the master branch
on:
  pull_request:
  push:
    branches: [master]

jobs:
  stack:
    name: stack / ghc ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stack: ["2.3.1"]
        ghc: ["8.8.3"]

    steps:
    - uses: actions/checkout@v2
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/master'

    - uses: actions/setup-haskell@v1.1.3
      name: Setup Haskell Stack
      with:
        ghc-version: ${{ matrix.ghc }}
        stack-version: ${{ matrix.stack }}

    - uses: actions/cache@v1
      name: Cache ~/.stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ matrix.ghc }}-stack-v2

    - uses: actions/cache@v1
      name: Cache ~/hpc-codecov (for coverage report generation)
      with:
        path: ~/hpc-codecov
        key: ${{ runner.os }}-${{ matrix.ghc }}-hpc-codecov-v1

    - name: Build
      run: |
        stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks

    - name: Test
      run: |
        stack test --system-ghc --coverage

    - name: Generate coverage report
      run: |
        stack install hpc-codecov --local-bin-path ~/hpc-codecov
        # this should actually be the search location below,
        # but does not work, so we search in .
        # HPCROOT=$(stack path --local-hpc-root)
        TIX=$(find . -name 'poseidon-tools-tests.tix')
        MIX=$(stack path --dist-dir)/hpc
        stack exec -- ~/hpc-codecov/hpc-codecov --mix=$MIX -o codecov.json $TIX

    - name: Upload coverage report
      run: bash <(curl -s https://codecov.io/bash)
